name: cordex-tutorials
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - cftime
  - netCDF4
  - xesmf
  - cdo
  - python-cdo
  - jupyter-book
  - intake-esm
  - ghp-import
  - esgf-pyclient
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git  # latest py-cordex version
