name: cordex-tutorials
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - dask
  - cftime
  - netCDF4
  - xesmf=0.7.1
  - cdo
  - python-cdo
  - jupyter-book
  - intake-esm
  - ghp-import
  - esgf-pyclient
  - s3fs
  - fsspec
  - boto3
  - ipykernel
  - jupyterlab
  - seaborn
  - tqdm
  - py-cordex>=0.6
#  - pip:
#    - git+https://github.com/euro-cordex/py-cordex.git  # latest py-cordex version
